### PR TITLE
Map current_range_meters as provided instead of setting a missing value to 0.0

### LINKED ISSUE #502: Vehicles with propulsion type human should not state current_range_meters=0
## Expected behavior
Vehicles with a `vehicle_type` that has `propulsion_type=human` should not state `current_range_meters=0`

## Observed behavior
Both `VehicleStatusFeedMappers`(v2.3 and v3.0) [set a missing current_range_meters to 0](https://github.com/entur/lamassu/blob/e8abc84f7b24ea9b941db277214c84ac4fab6aae/src/main/java/org/entur/lamassu/mapper/feedmapper/v3/VehicleStatusFeedMapper.java#L82) without regard to the vehicle's `propulsion_type`.

## Version of lamassu used (exact commit hash or JAR name)
e8abc84f7b24ea9b941db277214c84ac4fab6aae

### PR DESCRIPTION
**Pull request by hbruch**
### Summary

This PR maps a vehicle's `current_range_meters` as provided. A missing value is not set to a default of `0`, which would only be appropriate, if the vehicle_type's propulsion_type was not `human`. 

### Issue
Closes #502

### Unit tests

This PR updates `FreeBikeStatusFeedMapperTest.testMissingCurrentRangeMeters` to explicitly check, that missing `current_range_meters` is not filled in. While the test suggests an easy fix to just check the vehicle_type's propulsion_type by accessing it from `feedProvider.getVehicleTypes()`, this is usually not populated for harvested feeds, but would need explicit configuration.

### CODE REVIEW

**Comment by hbruch** [comment]
Hm. Not sure how the changes of this PR relate to the failing test (?)

**Comment by testower** [comment]
Re the failing test: can you try to close and reopen the PR

**Comment by hbruch** [comment]
Closing as suggested.

**Comment by hbruch** [comment]
Re-Opening as suggested.

**Comment by testower** [comment]
Do all the tests pass locally?

**Comment by hbruch** [comment]
Oh dear, no: 
```json
{"errors":[
  { 
    "message":"The field at path '/vehicles[0]/currentRangeMeters' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value.  The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'Float' within parent type 'Vehicle'",
    "path":["vehicles",0,"currentRangeMeters"],
    "extensions":{"classification":"NullValueInNonNullableField"}
  }]
}
```
Schema.graphql's type `Vehicle` currently declares `currentRangeMeters` as mandatory value (`currentRangeMeters: Float!`).

How would you resolve this? In the graphql query response return 0, even for propulsion type human? Or make it optional, which would be a potentially breaking change to the schema:
```
type Vehicle {
    id: ID!
    lat: Float!
    lon: Float!
    isReserved: Boolean!
    isDisabled: Boolean!
    currentRangeMeters: Float!
    ..
}
```

**Comment by testower** [comment]
Well that's a bummer. Obviously a mistake on my part. I'm leaning towards making it optional. It's strictly speaking not a breaking change. The other way around would be?

**Comment by testower** [comment]
I guess it can be considered breaking. Maybe returning 0 then is unavoidable...

**Comment by testower** [comment]
Seems like there's a formatting error now @hbruch

**Pull request merged**
