### PR TITLE
let CI publish Docker image, tweak Dockerfile

### PR DESCRIPTION
**Pull request by derhuerst**
This PR changes the CI config, on `master`, to build a Docker image and publish it as `entur/lamassu` to the Docker Hub.

---

*Note:* I cannot view the CI run's output without logging in, so you'll have to tell me if something is broken.
*Note:* You can [push into this PR's branch directly](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork), you don't need to create a separate PR.

### CODE REVIEW

**Comment by testower** [comment]
Thanks @derhuerst. I know realise there is a precedence for this in our projects, which is to build and push the image to github packages using github workflow. See https://github.com/entur/anshar/blob/master/.github/workflows/ci.yml

I can make the necessary changes.

**Comment by derhuerst** [comment]
@testower Any news on this? Do you prefer GitHub Actions or CircleCI?

**Comment by testower** [comment]
We're keeping circleci to build our own jar into our private repo, and then we'll use github actions for public builds. It's on my backlog. It's on my backlog :)

**Comment by derhuerst** [comment]
> It's on my backlog. It's on my backlog :)

I can contribute this!

> We're keeping circleci to build our own jar into our private repo, and then we'll use github actions for public builds.

I assume GitHub Actions should still replicate the tests running in CircleCI, so that it doesn't publish a faulty Docker image?

**Comment by testower** [comment]
> I can contribute this!

Thanks, appreciate it!

> > We're keeping circleci to build our own jar into our private repo, and then we'll use github actions for public builds.
> 
> I assume GitHub Actions should still replicate the tests running in CircleCI, so that it doesn't publish a faulty Docker image?

Correct :)

**Comment by testower** [comment]
@derhuerst It should also run tests and build image on pull requests actually (but not push the image of course)

**Comment by testower** [comment]
@derhuerst I'll probably opt for #246 instead using `jib-maven-plugin` to build the Docker image.

**Pull request closed without merging**
