### PR TITLE
Dockerfile: build lamassu

### PR DESCRIPTION
**Pull request by derhuerst**
This PR changes the `Dockerfile` to actually build lamassu, instead of just copying it from outside. This makes the Docker build fully self-contained, so I decided to move it to `/Dockerfile`.

Some further remarks:
- ~~Seemingly due to https://github.com/entur/lamassu/issues/189, the Docker build is currently broken.~~
- I have copied all `.gitignore` entries into `.dockerignore`.

### CODE REVIEW

**Comment by derhuerst** [comment]
The Docker build currently fails as follows:

```
 > [build 6/6] RUN --mount=type=bind,source=pom.xml,target=pom.xml     --mount=type=bind,source=.mvn,target=.mvn     --mount=type=bind,source=mvnw,target=mvnw     --mount=type=cache,target=/root/.m2/     ./mvnw install -DskipTests:
13.31 [INFO] Total time:  6.423 s
13.32 [INFO] Finished at: 2023-08-15T21:37:10Z
13.32 [INFO] ------------------------------------------------------------------------
13.34 [ERROR] Could not find goal '${plugin.prettier.goal}' in plugin com.hubspot.maven.plugins:prettier-maven-plugin:0.20 among available goals check, print-args, write -> [Help 1]
13.35 [ERROR] 
13.35 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
13.36 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
13.36 [ERROR] 
13.36 [ERROR] For more information about the errors and possible solutions, please read the following articles:
13.37 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoNotFoundException
```

Do you know what needs to be fixed? With `CI=true`, it fails as follows:

```
#10 [build 6/6] RUN --mount=type=bind,source=pom.xml,target=pom.xml     --mount=type=bind,source=.mvn,target=.mvn     --mount=type=bind,source=mvnw,target=mvnw     --mount=type=cache,target=/root/.m2/     env CI=true     ./mvnw install -DskipTests
#10 7.017 [INFO] Scanning for projects...
#10 12.94 [INFO] 
#10 12.94 [INFO] -------------------------< org.entur:lamassu >--------------------------
#10 12.94 [INFO] Building lamassu 0.0.1-SNAPSHOT
#10 12.95 [INFO] --------------------------------[ jar ]---------------------------------
#10 22.47 [INFO] 
#10 22.51 [INFO] --- maven-enforcer-plugin:3.0.0:enforce (enforce) @ lamassu ---
#10 24.65 [WARNING] Rule 1: org.apache.maven.plugins.enforcer.RequirePluginVersions warned with message:
#10 24.65 Some plugins are missing valid versions or depend on Maven 3.6.3 defaults: (LATEST RELEASE SNAPSHOT are not allowed)
#10 24.66 org.apache.maven.plugins:maven-site-plugin. 	The version currently in use is 3.3 via default lifecycle bindings
#10 24.66 
#10 24.67 [INFO] 
#10 24.67 [INFO] --- prettier-maven-plugin:0.20:check (default) @ lamassu ---
#10 26.67 qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
#10 26.75 [INFO] ------------------------------------------------------------------------
#10 26.76 [INFO] BUILD FAILURE
#10 26.77 [INFO] ------------------------------------------------------------------------
#10 26.80 [INFO] Total time:  19.858 s
#10 26.80 [INFO] Finished at: 2023-08-15T21:38:20Z
#10 26.80 [INFO] ------------------------------------------------------------------------
#10 26.81 [ERROR] Failed to execute goal com.hubspot.maven.plugins:prettier-maven-plugin:0.20:check (default) on project lamassu: Error downloading prettier-java, exit code: 255 -> [Help 1]
#10 26.81 [ERROR] 
#10 26.81 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
#10 26.81 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
#10 26.81 [ERROR] 
#10 26.81 [ERROR] For more information about the errors and possible solutions, please read the following articles:
#10 26.82 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
#10 ERROR: process "/bin/sh -c env CI=true     ./mvnw install -DskipTests" did not complete successfully: exit code: 1
```

**Comment by testower** [comment]
@derhuerst try adding `-Dprettier.skip=true` to mvn install command. I think style check isn't really needed here anyway.

**Comment by testower** [comment]
@derhuerst actually I'm seeing an occasional timeout error on downloading prettier in CI, so it might be that. My suggestion might not help for that, but could be useful either way

**Comment by derhuerst** [comment]
> I'm seeing an occasional timeout error on downloading prettier in CI, so it might be that. My suggestion might not help for that, but could be useful either way

Indeed, with both `-Dprettier.skip` & `-Dprettier.skip=true`, it still seems to try to download prettier.

**Comment by testower** [comment]
Ok it actually tries to download NodeJS since prettier needs it to run. So adding NodeJS to the build image should do the trick

**Comment by derhuerst** [comment]
Can you modify this PR so that the Docker build works? This ping-pong-style debugging is a bit cumbersome TBH.

**Comment by testower** [comment]
I have fixed the issue (and some others) and added a CI job to verify it https://github.com/entur/lamassu/pull/213

**Pull request closed without merging**
