### PR TITLE
Cleanup docker

### PR DESCRIPTION
**Pull request by testower**
Since #246 the Dockerfile isn't really needed in the root anymore. docker-compose users may decide if they want to use the public image ([available at docker.io/entur/lamassu](https://hub.docker.com/r/entur/lamassu)) or use this example dockerfile?

cc @derhuerst @hbruch

### CODE REVIEW

**Comment by derhuerst** [comment]
The "standalone" `Dockerfile` provides one advantage: It allows building an image without having installed Java tooling (JDK, Maven). However, I'm not sure if there is a target group behind this use case, given that those people who want to modify Lamassu code like have the tooling installed anyways.

**Comment by derhuerst** [comment]
from https://github.com/entur/lamassu/pull/246#issuecomment-1714163931:

> Note that the Docker image, as currently built by Jib, lacks the following:
> 
> * a `README.md`, which Docker Hub would pick up and render
> * [OCI image annotations](https://github.com/opencontainers/image-spec/blob/24a0e97ff255f0beba36da3014a4752905b5c30b/annotations.md#pre-defined-annotation-keys) like `org.opencontainers.image.documentation` or `org.opencontainers.image.licenses`, which various Docker-related tools read and display to provide a better DX

**Comment by testower** [comment]
Another oustanding issue: docker build should be verified on pull requests (but not push the image). Thanks for raising this @derhuerst

**Comment by testower** [comment]
> a README.md, which Docker Hub would pick up and render

As far as I can tell this has to be done separately. DockerHub doesn't look inside the image for a readme, it has to be uploaded manually or programatically.

> [OCI image annotations](https://github.com/opencontainers/image-spec/blob/24a0e97ff255f0beba36da3014a4752905b5c30b/annotations.md#pre-defined-annotation-keys) like org.opencontainers.image.documentation or org.opencontainers.image.licenses, which various Docker-related tools read and display to provide a better DX

Not sure I understand. JIB has an option to output the OCI format instead of Docker, but that's probably not what you had in mind?

**Comment by testower** [comment]
> Another oustanding issue: docker build should be verified on pull requests (but not push the image). Thanks for raising this @derhuerst

Fixed with jib:dockerBuild in test job

**Comment by derhuerst** [comment]
> > a `README.md`, which Docker Hub would pick up and render
> 
> As far as I can tell this has to be done separately. DockerHub doesn't look inside the image for a readme, it has to be uploaded manually or programatically.

But many other tools do (e.g. GitHub Packages, [`docker-pushrm`](https://github.com/christian-korneck/docker-pushrm), and Docker Desktop will do it soon). Also, one can always manually check the readme from the command line. This is a lot less error-prone, albeit not done often, than google-ing the tool's repo's readme, since one can be sure to have the right version.

IMHO there's no good reason *not to* add the readme to the image.

**Comment by derhuerst** [comment]
> > [OCI image annotations](https://github.com/opencontainers/image-spec/blob/24a0e97ff255f0beba36da3014a4752905b5c30b/annotations.md#pre-defined-annotation-keys) like org.opencontainers.image.documentation or org.opencontainers.image.licenses, which various Docker-related tools read and display to provide a better DX
> 
> Not sure I understand. JIB has an option to output the OCI format instead of Docker, but that's probably not what you had in mind?

AFAIK, but I'm not sure, there is the [Docker-proprietary format (*Image Manifest v2*)](https://docs.docker.com/registry/spec/manifest-v2-2/) and there is the [OCI format](https://github.com/opencontainers/image-spec/blob/367a53cec838b502c193399faeae9ce7ace65c50/spec.md). By now, all tooling, including Docker CLI & Docker Hub, *should* support both.

The OCI format also defines [annotations](https://github.com/opencontainers/image-spec/blob/367a53cec838b502c193399faeae9ce7ace65c50/annotations.md), which with certain pre-defined well-known annotations (e.g. `org.opencontainers.image.licenses`) that can be picked up by tooling (e.g. the Docker CLI, Docker Hub, quay.io, GitHub Packages, Kubernetes, etc.).

Even when building images in the Docker-proprietary format, one can add OCI annotations which will be picked up (e.g. [here on GitHub Packages](https://github.com/public-transport/gtfs-via-postgres/pkgs/container/gtfs-via-postgres/122623641?tag=4.8.0-alpha.0)). So, given that most of the ecosystem supports them, they should under many circumstances improve the UX for developers using the image.

**Comment by testower** [comment]
> IMHO there's no good reason not to add the readme to the image.

Not really arguing against it, just pointing out it's not a short-coming of jib per se as this would perhaps suggest "Note that the Docker image, as currently built by Jib, lacks the following:"

I would suggest creating a separate issue / PR for this.

> Not sure how to get JIB to put the annotations though.

This is beyond the scope of what we need at Entur and I'm not familiar with OCI. Feel free to contribute on this separately if you need it.

**Comment by derhuerst** [comment]
Just noticed that the current images are missing some helpful metadata.

```shell
docker image inspect docker.io/entur/lamassu:2024-07-15T11-30 | jq -r --tab '.[0]'
```

shortened for readability:

```json
{
	"Comment": "jvm arg files",
	"Created": "1970-01-01T00:00:00Z",
	"DockerVersion": "",
	"Author": "",
	"Config": {
		"Labels": {}
	},
	"Metadata": {
		"LastTagTime": "0001-01-01T00:00:00Z"
	}
}
```

---

Compare this to a `docker buildx build`-based image which also has [OCI annotations](https://github.com/opencontainers/image-spec/blob/v1.1.0/annotations.md#pre-defined-annotation-keys) in the `Dockerfile`. (Some are missing/wrong there, too.)

```shell
docker image inspect ghcr.io/mobidata-bw/postgis-with-pg-plan-filter:2024-05-15T15.25.26-d44ab82 | jq -r --tab '.[0]'
```

```json
[
	{
		"Comment": "buildkit.dockerfile.v0",
		"Created": "2024-05-15T15:25:39.210927025Z",
		"DockerVersion": "",
		"Author": "",
		"Config": {
			"Labels": {
				"maintainer": "PostGIS Project - https://postgis.net",
				"org.opencontainers.image.authors": "MobiData-BW IPL contributors <mobidata-bw@nvbw.de>",
				"org.opencontainers.image.description": "PostGIS Docker image with the pg_plan_filter extension.",
				"org.opencontainers.image.documentation": "https://github.com/mobidata-bw/postgis-with-pg-plan-filter",
				"org.opencontainers.image.licenses": "(EUPL-1.2)",
				"org.opencontainers.image.source": "https://github.com/mobidata-bw/postgis-with-pg-plan-filter",
				"org.opencontainers.image.title": "postgis-with-pg-plan-filter"
			}
		},
		"Metadata": {
			"LastTagTime": "0001-01-01T00:00:00Z"
		}
	}
]
```

While the metadata is not strictly necessary, various tools (GitHub Container Registry, Docker Registry, Docker CLI, [Renovate Bot](https://docs.renovatebot.com) , etc.) pick them up to provide smarter defaults and a better UX.

**Comment by testower** [comment]
Please refer to the previous comment from me in this PR. If you need this, create a new issue, and contribute a solution.

**Pull request merged**
